import type { Project } from "./types";

export const projects: Project[] = [
  {
    name: ["AdiClub", "Events"],
    meta: "Adidas · Community · Fitness",
    cards: [
      {
        kind: "media",
        label: "Event day video, 42s",
        ratio: "16:9",
        play: true,
        src: "/media/adiclub-2.mp4",
        poster: "/media/adiclub-2-poster.jpg",
        type: "video",
      },
      {
        kind: "media",
        tone: "deeper",
        label: "",
        ratio: "",
        src: "/media/adiclub-1.mp4",
        poster: "/media/adiclub-1-poster.jpg",
        type: "video",
      },
      {
        kind: "detail",
        head: ["Steam, crema,", "texture."],
        desc: "A tactile, macro-heavy product film for a limited seasonal release — paired with a stills set for packaging and web.",
        stats: [
          { num: "53s", k: "Hero film" },
          { num: "24", k: "Stills delivered" },
          { num: "9 days", k: "To sell-out" },
        ],
        link: "Watch the film",
      },
    ],
    caption: [
      "Single day filming and editing for AdiClub.",
      "Social media content, stills, event day recaps",
    ],
    year: "2024",
  },
  {
    name: ["Ebb & Flow", "Electrical"],
    meta: "Launch film · Social package · Hospitality",
    cards: [
      {
        kind: "media",
        label: "Hero film, 60s",
        ratio: "9:16",
        play: true,
        src: "/media/ebb-hero.mp4",
        poster: "/media/ebb-hero-poster.jpg",
        type: "video",
      },
      {
        kind: "media",
        tone: "deep",
        label: "Shortform reels, 10-15s",
        ratio: "16:9",
        play: true,
        src: "/media/ebb-brnt.mp4",
        poster: "/media/ebb-brnt-poster.jpg",
        type: "video",
        fit: "contain",
      },
      {
        kind: "media",
        tone: "deep",
        label: "Shortform reels, 10-15s",
        ratio: "16:9",
        play: true,
        src: "/media/ebb-reel.mp4",
        poster: "/media/ebb-reel-poster.jpg",
        type: "video",
        fit: "contain",
      },
      {
        kind: "detail",
        head: ["One shoot day,", "live by opening night."],
        desc: "A launch film for a new taproom — one hero edit plus six vertical cutdowns built for paid social, delivered before opening weekend.",
        stats: [
          { num: "1+6", k: "Deliverables" },
          { num: "48h", k: "Turnaround" },
          { num: "210K", k: "Views, 30 days" },
        ],
        link: "Watch the film",
      },
    ],
    caption: [
      "Launch film and social package for a new Melbourne taproom.",
      "Direction, shoot, edit, colour, cutdowns",
    ],
    year: "2025",
  },
  {
    name: ["Wicker Darling", "Series"],
    meta: "Season coverage · Same-day edits · Event",
    cards: [
      {
        kind: "media",
        tone: "deeper",
        label: "Round 2 recap",
        ratio: "9:16",
        src: "/media/wicker-unicorns.jpg",
        type: "image",
        fit: "cover",
      },
      {
        kind: "media",
        tone: "deep",
        label: "Shortform reel, 8s",
        ratio: "16:9",
        play: true,
        src: "/media/wicker-dino-reel.mp4",
        poster: "/media/wicker-dino-reel-poster.jpg",
        type: "video",
        fit: "contain",
      },
      {
        kind: "media",
        tone: "deep",
        label: "Unpacking video, 38s",
        ratio: "16:9",
        play: true,
        src: "/media/wicker-unpacking.mp4",
        poster: "/media/wicker-unpacking-poster.jpg",
        type: "video",
        fit: "contain",
      },
      {
        kind: "detail",
        head: ["Recaps dropped while the crowd", "was still buzzing."],
        desc: "Trackside coverage across a three-round series — same-day recap reels plus a season highlight film for sponsors.",
        stats: [
          { num: "3", k: "Rounds covered" },
          { num: "Same day", k: "Recap reels" },
          { num: "100k+", k: "Follower increase" },
        ],
        link: "Watch the season film",
      },
    ],
    caption: [
      "Season-long trackside content partner for an independent Wicker handbag brand.",
      "Direction, shoot, edit, reel creation, sponsor deliverables",
    ],
    year: "2023–26",
  },
  {
    name: ["Tonle", "Candles"],
    meta: "Branding · Website Mockup · Product Photography",
    cards: [
      {
        kind: "media",
        tone: "deeper",
        label: "Product photography, Single shot",
        ratio: "9:16",
        play: true,
        src: "/media/tonle-product-1.jpg",
        type: "image",
      },
      {
        kind: "media",
        label: "Product photography, Product packaging",
        ratio: "9:16",
        src: "/media/tonle-product-2.jpg",
        type: "image",
      },
      {
        kind: "media",
        tone: "deep",
        label: "Website mockup",
        ratio: "16:9",
        src: "/media/tonle-mockup.png",
        type: "image",
      },
      {
        kind: "media",
        tone: "deep",
        label: "Branding artboards",
        ratio: "16:9",
        src: "/media/tonle-branding-artboard.png",
        type: "image",
      },
      {
        kind: "detail",
        head: ["A rolling", "content engine."],
        desc: "Twelve pieces a month across trainer spotlights, class energy and member stories. Consistent output, zero content droughts.",
        stats: [
          { num: "12", k: "Pieces / month" },
          { num: "14 mo", k: "Retainer running" },
          { num: "60+", k: "Leads attributed" },
        ],
        link: "See the feed",
      },
    ],
    caption: [
      "Product launch and branding project for Tonle Candles.",
      "Logo design, product photography, branding artboards, website mockup",
    ],
    year: "2025",
  },
  {
    name: ["Alpha", "Sports Medicine"],
    meta: "Informative · Social Media · Fitness",
    cards: [
      {
        kind: "media",
        label: "About Us Video, 13s",
        ratio: "16:9",
        play: true,
        src: "/media/hype-video.mp4",
        poster: "/media/hype-video-poster.jpg",
        type: "video",
      },
      {
        kind: "media",
        tone: "deeper",
        label: "Pour sequence, macro",
        ratio: "4:5",
        src: "/media/alpha-1.jpg",
        type: "image",
      },
      {
        kind: "media",
        tone: "deep",
        label: "Stills set, 24 frames",
        ratio: "4:5",
        src: "/media/alpha-2.jpg",
        type: "image",
      },
      {
        kind: "detail",
        head: ["Steam, crema,", "texture."],
        desc: "A tactile, macro-heavy product film for a limited seasonal release — paired with a stills set for packaging and web.",
        stats: [
          { num: "53s", k: "Hero film" },
          { num: "24", k: "Stills delivered" },
          { num: "9 days", k: "To sell-out" },
        ],
        link: "Watch the film",
      },
    ],
    caption: [
      "Monthly content retainer for a Sports Medicine clinic.",
      "Social media content, stills, trainer spotlights, practitioner interviews",
    ],
    year: "2024",
  },
  {
    name: ["Alex M", "Events"],
    meta: "Entertainment · Same-day edits · Events",
    cards: [
      {
        kind: "media",
        tone: "deep",
        label: "Walkthrough, 2 min",
        ratio: "16:9",
        play: true,
        src: "/media/alex-social-cut.mp4",
        poster: "/media/alex-social-cut-poster.jpg",
        type: "video",
      },
      {
        kind: "media",
        tone: "deeper",
        label: "Studio day",
        ratio: "16:9",
        src: "/media/alex-studio.mp4",
        poster: "/media/alex-studio-poster.jpg",
        type: "video",
      },
      {
        kind: "detail",
        head: ["Graded overnight,", "inbox by Monday."],
        desc: "A cinematic walkthrough and aerial package for a flagship development launch — shot at golden hour, delivered in 48 hours.",
        stats: [
          { num: "1+3", k: "Hero + cuts" },
          { num: "48h", k: "Turnaround" },
          { num: "40k+", k: "Impressions" },
        ],
        link: "",
      },
    ],
    caption: [
      "Flagship development launch film and aerials.",
      "Walkthrough, aerial, colour grade, agent cutdowns",
    ],
    year: "2026",
  },
];
