import type { Project } from "./types";

export const projects: Project[] = [
  {
    name: ["AdiClub", "Events"],
    meta: "Adidas · Community · Fitness",
    cards: [
      {
        kind: "media",
        label: "Event day video, 42s",
        ratio: "16:9",
        play: true,
        src: "/media/adiclub-2.mp4",
        poster: "/media/adiclub-2-poster.jpg",
        type: "video",
      },
      {
        kind: "media",
        tone: "deeper",
        label: "Run club recap, 39s",
        ratio: "16:9",
        src: "/media/adiclub-1.mp4",
        poster: "/media/adiclub-1-poster.jpg",
        type: "video",
      },
      {
        kind: "detail",
        head: ["One morning,", "run club to coffee."],
        desc: "An Adidas run club session that finished up at a local cafe — covered end to end across a single morning, then cut into a hero recap and vertical pieces built for social.",
        stats: [
          { num: "1 day", k: "On location" },
          { num: "2", k: "Hero edits" },
          { num: "6", k: "Social cutdowns" },
        ],
        link: "Watch the recap",
      },
    ],
    caption: [
      "Single day filming and editing for AdiClub.",
      "Social media content, stills, event day recaps",
    ],
    year: "2024",
  },
  {
    name: ["Ebb & Flow", "Electrical"],
    meta: "Brand film · Social package · Trade",
    cards: [
      {
        kind: "media",
        label: "Hero film, 90s",
        ratio: "9:16",
        play: true,
        src: "/media/ebb-hero.mp4",
        poster: "/media/ebb-hero-poster.jpg",
        type: "video",
      },
      {
        kind: "media",
        tone: "deep",
        label: "Shortform reels, 10-15s",
        ratio: "16:9",
        play: true,
        src: "/media/ebb-brnt.mp4",
        poster: "/media/ebb-brnt-poster.jpg",
        type: "video",
        fit: "contain",
      },
      {
        kind: "media",
        tone: "deep",
        label: "Shortform reels, 10-15s",
        ratio: "16:9",
        play: true,
        src: "/media/ebb-reel.mp4",
        poster: "/media/ebb-reel-poster.jpg",
        type: "video",
        fit: "contain",
      },
      {
        kind: "detail",
        head: ["Trade work,", "shot like a brand."],
        desc: "A brand film for an electrical contractor, plus a set of shortform reels — the kind of work that usually never gets filmed, cut so it holds attention in a feed.",
        stats: [
          { num: "1+2", k: "Deliverables" },
          { num: "90s", k: "Hero film" },
          { num: "2 wks", k: "Turnaround" },
        ],
        link: "Watch the film",
      },
    ],
    caption: [
      "Brand film and social package for a Melbourne electrical contractor.",
      "Direction, shoot, edit, colour, cutdowns",
    ],
    year: "2025",
  },
  {
    name: ["Wicker Darling", "Series"],
    meta: "Product reels · Ongoing content · Retail",
    cards: [
      {
        kind: "media",
        tone: "deeper",
        label: "Unicorn range, stills",
        ratio: "9:16",
        src: "/media/wicker-unicorns.jpg",
        type: "image",
        fit: "cover",
      },
      {
        kind: "media",
        tone: "deep",
        label: "Shortform reel, 8s",
        ratio: "16:9",
        play: true,
        src: "/media/wicker-dino-reel.mp4",
        poster: "/media/wicker-dino-reel-poster.jpg",
        type: "video",
        fit: "contain",
      },
      {
        kind: "media",
        tone: "deep",
        label: "Unpacking video, 38s",
        ratio: "16:9",
        play: true,
        src: "/media/wicker-unpacking.mp4",
        poster: "/media/wicker-unpacking-poster.jpg",
        type: "video",
        fit: "contain",
      },
      {
        kind: "detail",
        head: ["Bags with", "a sense of humour."],
        desc: "Ongoing content for an independent wicker handbag label — product reels, unboxings and stills that keep pace with a range that never takes itself too seriously.",
        stats: [
          { num: "3 yrs", k: "Working together" },
          { num: "40+", k: "Reels delivered" },
          { num: "100k+", k: "Follower growth" },
        ],
        link: "See the range",
      },
    ],
    caption: [
      "Ongoing content partner for an independent wicker handbag brand.",
      "Direction, shoot, edit, reel creation, product stills",
    ],
    year: "2023–26",
  },
  {
    name: ["Tonle", "Candles"],
    meta: "Branding · Website Mockup · Product Photography",
    cards: [
      {
        kind: "media",
        tone: "deeper",
        label: "Product photography, Single shot",
        ratio: "9:16",
        play: true,
        src: "/media/tonle-product-1.jpg",
        type: "image",
      },
      {
        kind: "media",
        label: "Product photography, Product packaging",
        ratio: "9:16",
        src: "/media/tonle-product-2.jpg",
        type: "image",
      },
      {
        kind: "media",
        tone: "deep",
        label: "Website mockup",
        ratio: "16:9",
        src: "/media/tonle-mockup.png",
        type: "image",
      },
      {
        kind: "media",
        tone: "deep",
        label: "Branding artboards",
        ratio: "16:9",
        src: "/media/tonle-branding-artboard.png",
        type: "image",
      },
      {
        kind: "detail",
        head: ["A candle brand,", "built from scratch."],
        desc: "Full identity for a small-batch candle maker — logo and branding artboards, product photography for packaging and web, and a site mockup to bring it all together.",
        stats: [
          { num: "1", k: "Brand identity" },
          { num: "30+", k: "Product shots" },
          { num: "6 wks", k: "Concept to launch" },
        ],
        link: "See the branding",
      },
    ],
    caption: [
      "Product launch and branding project for Tonle Candles.",
      "Logo design, product photography, branding artboards, website mockup",
    ],
    year: "2025",
  },
  {
    name: ["Alpha", "Sports Medicine"],
    meta: "Informative · Social Media · Sports Science",
    cards: [
      {
        kind: "media",
        label: "About Us Video, 13s",
        ratio: "16:9",
        play: true,
        src: "/media/hype-video.mp4",
        poster: "/media/hype-video-poster.jpg",
        type: "video",
      },
      {
        kind: "media",
        tone: "deeper",
        label: "Treatment room",
        ratio: "4:5",
        src: "/media/alpha-1.jpg",
        type: "image",
      },
      {
        kind: "media",
        tone: "deep",
        label: "Rehab gym floor",
        ratio: "4:5",
        src: "/media/alpha-2.jpg",
        type: "image",
      },
      {
        kind: "detail",
        head: ["Sports science,", "made watchable."],
        desc: "Monthly content for a sports science clinic — an About Us film that gives the space a face, plus practitioner spotlights and stills for the website and socials.",
        stats: [
          { num: "13s", k: "About Us film" },
          { num: "12", k: "Pieces / month" },
          { num: "18 mo", k: "Retainer running" },
        ],
        link: "Watch the film",
      },
    ],
    caption: [
      "Monthly content retainer for a Sports Medicine clinic.",
      "Social media content, stills, trainer spotlights, practitioner interviews",
    ],
    year: "2024",
  },
  {
    name: ["Alex M", "Events"],
    meta: "DJ · Studio & live · Entertainment",
    cards: [
      {
        kind: "media",
        tone: "deep",
        label: "Live set, 15s",
        ratio: "16:9",
        play: true,
        src: "/media/alex-social-cut.mp4",
        poster: "/media/alex-social-cut-poster.jpg",
        type: "video",
      },
      {
        kind: "media",
        tone: "deeper",
        label: "Studio BTS, 12s",
        ratio: "16:9",
        src: "/media/alex-studio.mp4",
        poster: "/media/alex-studio-poster.jpg",
        type: "video",
      },
      {
        kind: "detail",
        head: ["Studio to stage,", "one story."],
        desc: "Content for a DJ across both halves of the job — close-quarters behind the scenes while tracks come together, and the room going off during a live set.",
        stats: [
          { num: "2", k: "Shoots" },
          { num: "Same week", k: "Delivery" },
          { num: "40k+", k: "Impressions" },
        ],
        link: "Watch the set",
      },
    ],
    caption: [
      "Studio and live event content for a Melbourne DJ.",
      "Direction, shoot, edit, colour grade, social cutdowns",
    ],
    year: "2026",
  },
];
